# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e0c8bfcc0e233f8a65b3a15ca18123b53d78c9ee730e0e1f204b1a46567df0a4dbd0076a12e21c243498b8cc6c8a0710f3e5e8b47df0c151c91965e9d91797ac
  gmail_password: <%= ENV["GMAIL_PASSWORD"] %>

test:
  secret_key_base: 2873327665671e9bdadd3bda990a7dd7340c2631e73ab6a8bd125d47217ea86c17210deb1c0ff12c707f0627a28cfb305e8ec47266bc78900ad4949baf08523e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  gmail_password: <%= ENV["GMAIL_PASSWORD"] %>
